using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Media;
namespace Prometheus.DriveController;
public partial class MainWindow:Window{
 readonly LegacyControllerBridge _bridge=new(); readonly StartupProbe _probe=new();
 static readonly Brush Green=new SolidColorBrush(Color.FromRgb(25,195,125)), Yellow=new SolidColorBrush(Color.FromRgb(228,183,44)), Red=new SolidColorBrush(Color.FromRgb(239,68,68)), Muted=new SolidColorBrush(Color.FromRgb(129,153,170));
 readonly System.Windows.Threading.DispatcherTimer _timer=new(){Interval=TimeSpan.FromSeconds(5)};
 bool _operationActive,_refreshing,_ejecting,_desiredRunning=File.Exists(DesiredStatePath),_repairing; int _repairAttempts; DateTime _nextRepair=DateTime.MinValue; const int MaxRepairAttempts=3; static string DesiredStatePath=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Prometheus","desired-running.flag"); void SetDesired(bool value){_desiredRunning=value;Directory.CreateDirectory(Path.GetDirectoryName(DesiredStatePath)!);if(value)File.WriteAllText(DesiredStatePath,DateTime.Now.ToString("o"));else if(File.Exists(DesiredStatePath))File.Delete(DesiredStatePath);}
 public MainWindow(){InitializeComponent();InitializeArrivalObserver();ShowPlan(ProgressPlan.Startup);Loaded+=async(_,_)=>{if(Environment.GetCommandLineArgs().Contains("--verify-layout")){_desiredRunning=false;return;}try{_refreshing=true;await RefreshAsync();}catch(Exception ex){Log(ex.Message);}finally{_refreshing=false;}};Closing+=OnClosing;_timer.Tick+=async(_,_)=>{if(_operationActive||_refreshing||_ejecting)return;_refreshing=true;try{await RefreshAsync();}catch(Exception ex){Visual("red");EjectText.Text="No";Log(ex.Message);}finally{_refreshing=false;}};_timer.Start();var args=Environment.GetCommandLineArgs();if(args.Length==3&&args[1]=="--verify-layout")Loaded+=async(_,_)=>await VerifyLayoutAsync(args[2]);}
 void Visual(string phase){var b=phase=="green"?Green:phase=="red"?Red:Yellow;StatusBorder.BorderBrush=b;StateText.Foreground=b;EjectText.Foreground=b;}
 string _lastLog=""; void Log(string s){if(s==_lastLog)return;_lastLog=s;if(LogText.Text.Length>50000)LogText.Text=LogText.Text[^25000..];LogText.AppendText($"[{DateTime.Now:HH:mm:ss}] {s}{Environment.NewLine}");LogText.ScrollToEnd();}
 IEnumerable<ProgressStep> _plan=ProgressPlan.Startup;
 ISet<string> _lastCompleted=new HashSet<string>();
 bool _startupFailed;
 public sealed record StepRow(string Label,string WeightText,string State,string Icon,Brush Color,int Value,string Detail);
 void ShowPlan(IEnumerable<ProgressStep> steps,ISet<string>? completed=null,bool ready=false){
 _plan=steps;_lastCompleted=completed??new HashSet<string>();
 var a=steps.Select(x=>x with{Complete=_lastCompleted.Contains(x.Name)}).ToArray();
 StepsList.ItemsSource=a.Select(x=>{
 bool error=!x.Complete&&(_startupFailed||(!_operationActive&&x.Name.StartsWith("Verify"))||(!_operationActive&&x.Name.StartsWith("Validate")));
 var state=x.Complete?"Passed":error?"Issue":_operationActive?"Checking":"Stopped";
 return new StepRow(Short(x.Name),$"{x.Weight}%",state,x.Complete?"●":error?"●":"●",x.Complete?Green:error?Red:Yellow,x.Complete?100:0,x.Complete?"Check passed":error?"Check did not pass. See live log.":_operationActive?"Waiting for measured confirmation":"Service stopped or check pending");
 }).ToArray();
 var pct=ProgressPlan.Percent(a);OverallProgress.Value=ready?100:pct;PercentText.Text=ready?"Ready":$"{pct}%";
 }
 static string DriveSummary(string root){try{var di=new DriveInfo(root);double tb=di.TotalSize/1099511627776d,free=di.AvailableFreeSpace/1099511627776d;return $"{tb:F2} TB total • {free:F2} TB free • Prometheus • {di.DriveFormat} • {root}";}catch{return $"Prometheus • filesystem unavailable • {root}";}}
 static string Short(string s)=>s.Replace("Verify Prometheus SSD identity","SSD identity").Replace("Validate portable runtime","Portable runtime").Replace("Start Ollama service","Ollama service").Replace("Load configured model","Model load").Replace("Verify local memory database","Memory database").Replace("Verify portable model store","Model store").Replace("Verify Prometheus source tree","Source tree").Replace("Open chat runtime","Chat runtime");
 async Task RefreshAsync(){if(File.Exists(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Prometheus","eject-mode.json"))){ObserveEjectState();return;}var root=_probe.FindPrometheusDrive();DriveInfoText.Text=root==null?"Not detected":DriveSummary(root);DeviceText.Text=$"SSD: {(root??"Not detected")}";if(root==null){DriveStateText.Text="Missing / unreadable";DriveStateText.Foreground=Red;Visual("red");StateText.Text="STATUS: SSD MISSING";ActivityText.Text="Prometheus SSD is not mounted as a readable volume.";EjectText.Text="No";StartButton.IsEnabled=false;StopButton.IsEnabled=false;return;}var health=_probe.DriveHealth(root);DriveStateText.Text=health.Healthy?"● READABLE":"● ERROR";DriveStateText.Foreground=health.Healthy?Green:Red;if(!health.Healthy){Visual("red");StateText.Text="STATUS: SSD ERROR";ActivityText.Text=health.Message+" Windows disk repair may be required; Prometheus will not write to the drive until it is readable.";OperationText.Text="Volume check";EjectText.Text="No";StartButton.IsEnabled=false;StopButton.IsEnabled=false;Log("SSD health: "+health.Message);return;}var done=await _probe.MeasureAsync(root);UpdateComponents(done);ShowPlan(ProgressPlan.Startup,done);if(_desiredRunning){await WatchdogAsync(root,done);if(_repairing)return;}ApplyStatus(await _bridge.RunAsync("status",root.TrimEnd('\\')));}
 async Task WatchdogAsync(string root,ISet<string> done){
  var missing=new[]{"Start Ollama service","Load configured model","Open chat runtime"}.Where(x=>!done.Contains(x)).ToArray();
  if(missing.Length==0){_repairAttempts=0;_nextRepair=DateTime.MinValue;RepairText.Text="WATCHDOG: HEALTHY / ALL RUNTIME CHECKS PASS";RepairText.Foreground=Green;return;}
  if(_repairing||DateTime.Now<_nextRepair)return;
  if(_repairAttempts>=MaxRepairAttempts){RepairText.Text=$"WATCHDOG: REPAIR FAILED AFTER {_repairAttempts}/{MaxRepairAttempts} ATTEMPTS";RepairText.Foreground=Red;Visual("red");StateText.Text="STATUS: REPAIR REQUIRED";ActivityText.Text="Automatic recovery reached its retry limit. See live log.";return;}
  _repairing=true;_repairAttempts++;RepairText.Text=$"WATCHDOG: REPAIRING {_repairAttempts}/{MaxRepairAttempts} ? {string.Join(", ",missing.Select(Short))}";RepairText.Foreground=Yellow;Visual("yellow");StateText.Text="STATUS: SELF-REPAIR";ActivityText.Text="Restarting the trusted Prometheus startup sequence and verifying measured health.";OperationText.Text="Self-repair";Log($"Watchdog repair attempt {_repairAttempts}/{MaxRepairAttempts}: {string.Join(", ",missing.Select(Short))}");
  try{var r=await _bridge.RunAsync("start",root.TrimEnd('\\'));Log($"Repair launcher: {r.Status?.Message??r.StdErr}");if(missing.Contains("Load configured model")){RepairText.Text=$"WATCHDOG: REPAIRING {_repairAttempts}/{MaxRepairAttempts} ? warming local model";Log("Watchdog is warming the configured local model.");await _probe.WarmModelAsync();}for(int i=0;i<40;i++){await Task.Delay(500);var measured=await _probe.MeasureAsync(root);UpdateComponents(measured);ShowPlan(ProgressPlan.Startup,measured);if(new[]{"Start Ollama service","Load configured model","Open chat runtime"}.All(measured.Contains)){_repairAttempts=0;RepairText.Text="WATCHDOG: RECOVERED / RUNTIME HEALTHY";RepairText.Foreground=Green;Visual("yellow");StateText.Text="STATUS: RUNNING";ActivityText.Text="Watchdog recovery succeeded and all runtime checks passed.";OperationText.Text="Running";Log("Watchdog recovery succeeded.");return;}}_nextRepair=DateTime.Now.AddSeconds(Math.Min(30,5*_repairAttempts));RepairText.Text=$"WATCHDOG: RETRY {_repairAttempts}/{MaxRepairAttempts} FAILED ? NEXT CHECK {_nextRepair:HH:mm:ss}";RepairText.Foreground=_repairAttempts>=MaxRepairAttempts?Red:Yellow;Log("Watchdog repair attempt did not restore all runtime checks.");}finally{_repairing=false;}
 }

 void UpdateComponents(ISet<string> d){Set(SsdComponent,"SSD Detection",d.Contains("Verify Prometheus SSD identity"));Set(RuntimeComponent,"Runtime (Python)",d.Contains("Validate portable runtime"));Set(OllamaComponent,"Ollama Service",d.Contains("Start Ollama service"));Set(ModelComponent,"Model Load",d.Contains("Load configured model"));Set(MemoryComponent,"Memory DB",d.Contains("Verify local memory database"));Set(StoreComponent,"Model Store",d.Contains("Verify portable model store"));Set(SourceComponent,"Source Tree",d.Contains("Verify Prometheus source tree"));Set(ChatComponent,"Chat Runtime",d.Contains("Open chat runtime"));}
 void Set(System.Windows.Controls.TextBlock t,string name,bool ok){t.Text=$"● {name} — {(ok?"Ready":"Stopped / unavailable")}";t.Foreground=ok?Green:Yellow;}
 void ApplyStatus(BridgeResult r){var s=r.Status;if(s==null){Visual("red");StateText.Text="STATUS: BLOCKED";ActivityText.Text="Controller unavailable. Check details in the log.";OperationText.Text="Error";EjectText.Text="No";Log(r.StdErr.Length>0?r.StdErr:"Unable to parse controller response.");return;}Visual(s.Phase??"yellow");StateText.Text=$"STATUS: {(s.Phase=="green"?"READY":s.Phase?.ToUpperInvariant())}";ActivityText.Text=s.Message??"Prometheus controller";OperationText.Text=s.Phase=="green"?"Stopped":s.Phase=="red"?"Blocked":"Running / checking";EjectText.Text="No";Log($"Controller: {s.Message} {s.Activity}");StartButton.IsEnabled=s.Phase=="green";StopButton.IsEnabled=s.Phase!="green";}
 async void Start_Click(object sender,RoutedEventArgs e){if(_operationActive||_refreshing||_ejecting)return;SetDesired(true);StartButton.Content="Start Prometheus";EjectButton.Content="Eject & verify";_repairAttempts=0;_nextRepair=DateTime.MinValue;RepairText.Text="WATCHDOG: ARMED / STARTUP EXPECTED";RepairText.Foreground=Yellow;_startupFailed=false;_timer.Start();_operationActive=true;try{var root=_probe.FindPrometheusDrive();if(root==null){await RefreshAsync();return;}var sw=Stopwatch.StartNew();StartButton.IsEnabled=false;StopButton.IsEnabled=true;Visual("yellow");StateText.Text="STATUS: STARTING";ActivityText.Text="Measured startup checks are running.";OperationText.Text="Startup";EjectText.Text="No";ShowPlan(ProgressPlan.Startup);Log("Startup requested.");var r=await _bridge.RunAsync("start",root.TrimEnd('\\'));ApplyStatus(r);if(r.ExitCode!=0)return;await _probe.WarmModelAsync();for(int i=0;i<60;i++){var done=await _probe.MeasureAsync();UpdateComponents(done);ShowPlan(ProgressPlan.Startup,done);if(done.Count==ProgressPlan.Startup.Length){sw.Stop();Visual("yellow");StateText.Text="STATUS: RUNNING";ActivityText.Text="All measured startup checks passed.";OperationText.Text="Running";EjectText.Text="No";ElapsedText.Text=$"Startup completed in {sw.Elapsed.TotalSeconds:F1} seconds.";StartupTimeText.Text=$"{sw.Elapsed.TotalSeconds:F1} seconds\n{DateTime.Now:g}";Log("All startup measurements passed.");return;}await Task.Delay(500);}sw.Stop();_startupFailed=true;ShowPlan(ProgressPlan.Startup,_lastCompleted);Visual("red");StateText.Text="STATUS: STARTUP INCOMPLETE";ElapsedText.Text="Startup checks timed out; incomplete rows are red.";Log("Startup measurement timed out.");}catch(Exception ex){Visual("red");EjectText.Text="No";Log(ex.Message);}finally{_operationActive=false;}}
 async void Stop_Click(object sender,RoutedEventArgs e){if(_operationActive||_refreshing||_ejecting)return;SetDesired(false);_repairAttempts=0;RepairText.Text="WATCHDOG: DISARMED / INTENTIONAL STOP";RepairText.Foreground=Muted;_operationActive=true;try{var root=_probe.FindPrometheusDrive();if(root==null){await RefreshAsync();return;}var sw=Stopwatch.StartNew();StartButton.IsEnabled=false;StopButton.IsEnabled=false;Visual("yellow");StateText.Text="STATUS: STOPPING / VERIFYING";ActivityText.Text="Graceful shutdown and eject-readiness checks are running.";OperationText.Text="Shutdown";EjectText.Text="No";var done=new HashSet<string>{"Request graceful chat shutdown"};ShowPlan(ProgressPlan.Shutdown,done);Log("Graceful shutdown requested.");var r=await _bridge.RunAsync("stop",root.TrimEnd('\\'));sw.Stop();if(r.ExitCode==0&&r.Status?.Phase=="green"){foreach(var check in r.Status.Checks??[])done.Add(check);ShowPlan(ProgressPlan.Shutdown,done);Visual("green");StateText.Text="STATUS: STOPPED";ActivityText.Text="Prometheus is stopped; Windows removal is still required.";OperationText.Text="Idle";EjectText.Text="No";ElapsedText.Text=$"Shutdown and verification completed in {sw.Elapsed.TotalSeconds:F1} seconds.";ShutdownTimeText.Text=$"{sw.Elapsed.TotalSeconds:F1} seconds\n{DateTime.Now:g}";VerifyTimeText.Text=$"Passed\n{DateTime.Now:g}";StartButton.IsEnabled=true;_timer.Stop();Log("Prometheus stopped. Use Safely Eject SSD to request Windows removal.");ActivityText.Text="Prometheus stopped; Windows has not released the SSD yet.";OperationText.Text="Stopped";}else{ApplyStatus(r);ElapsedText.Text="Shutdown blocked; see controller status and log.";Log("Shutdown verification did not reach green.");}}catch(Exception ex){Visual("red");EjectText.Text="No";Log(ex.Message);}finally{_operationActive=false;}}

 async void OpenChat_Click(object sender,RoutedEventArgs e){
  if(_operationActive||_refreshing||_ejecting)return;
  try{var root=_probe.FindPrometheusDrive();if(root==null){await RefreshAsync();return;}
   if(ChatWindow.Focus(root)){Log("Existing Prometheus chat brought forward.");return;}
   var measured=await _probe.MeasureAsync(root);
   if(measured.Contains("Open chat runtime")){Log("A chat is already running. Use its existing terminal, or Stop then Open Chat to replace an older hidden session.");return;}
   Start_Click(sender,e);
  }catch(Exception ex){Log("Unable to open chat: "+ex.Message);}
 }
 async void Eject_Click(object sender,RoutedEventArgs e){await DepartAsync();}
 async Task DepartAsync(){
 if(_operationActive||_refreshing||_ejecting)return;
 SetDesired(false);_repairAttempts=0;RepairText.Text="WATCHDOG: DISARMED / EJECT";RepairText.Foreground=Muted;_ejecting=true;_timer.Stop();EjectButton.IsEnabled=false;StartButton.IsEnabled=false;StopButton.IsEnabled=false;
 try{
 var root=_probe.FindPrometheusDrive();if(root==null){Log("No mounted Prometheus SSD to eject.");return;}
 Visual("yellow");StateText.Text="STATUS: PREPARING EJECT";ActivityText.Text="Closing chat and verifying databases before Windows removal.";OperationText.Text="Safe eject";EjectText.Text="No";
 var script=Path.Combine(AppContext.BaseDirectory,"Prometheus-Eject-Orchestrator.ps1");
 if(!File.Exists(script))throw new FileNotFoundException("Safe eject helper is missing.",script);
 var psi=new ProcessStartInfo("powershell.exe"){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true,WorkingDirectory=AppContext.BaseDirectory};
 foreach(var arg in new[]{"-NoProfile","-ExecutionPolicy","Bypass","-File",script,"-Drive",root.TrimEnd('\\')})psi.ArgumentList.Add(arg);
 using var process=Process.Start(psi)??throw new InvalidOperationException("Could not request Windows removal.");
 var output=process.StandardOutput.ReadToEndAsync();var error=process.StandardError.ReadToEndAsync();using var deadline=new CancellationTokenSource(TimeSpan.FromSeconds(240));await process.WaitForExitAsync(deadline.Token);var details=await output;var errors=await error;Log(details+errors);
 if(process.ExitCode==0&&_probe.FindPrometheusDrive()==null){Visual("green");StateText.Text="SAFE TO REMOVE";ActivityText.Text="Windows confirmed removal. Unplug the SSD; services will resume after disconnection.";EjectText.Text="Yes";DriveStateText.Text="Released";OperationText.Text="Ejected";ShowPlan(ProgressPlan.Shutdown,new HashSet<string>(ProgressPlan.Shutdown.Select(x=>x.Name)));}
 else{Visual("red");StateText.Text="STATUS: EJECT BLOCKED";ActivityText.Text="Windows still holds the SSD. Keep it connected; see the veto details in the live log.";OperationText.Text="Windows veto";EjectText.Text="No";}
 }catch(Exception ex){Visual("red");StateText.Text="STATUS: EJECT ERROR";EjectText.Text="No";Log(ex.Message);}
 finally{_ejecting=false;EjectButton.IsEnabled=true;EjectButton.Content="Retry eject";StartButton.Content="Resume Prometheus";var mounted=_probe.FindPrometheusDrive()!=null;StartButton.IsEnabled=mounted;_timer.Stop();}
 }
 void OpenFolder(string path){try{if(!Directory.Exists(path)){Log("Folder is unavailable: "+path);return;}Process.Start(new ProcessStartInfo("explorer.exe"){UseShellExecute=true,ArgumentList={path}});}catch(Exception ex){Log(ex.Message);}}
 void Knowledge_Click(object sender,RoutedEventArgs e){if(_ejecting||StartupProbe.EjectSuppressed)return;var root=_probe.FindPrometheusDrive();if(root!=null)OpenFolder(Path.Combine(root,"Prometheus-Resources","Knowledge"));}
 void Logs_Click(object sender,RoutedEventArgs e){OpenFolder(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Prometheus"));}
 async void Settings_Click(object sender,RoutedEventArgs e){
  if(_operationActive||_refreshing||_ejecting||StartupProbe.EjectSuppressed)return;
  try{var root=_probe.FindPrometheusDrive();if(root==null){Log("Connect Prometheus to inspect its settings.");return;}var p=await _probe.HardwareProfileAsync(root,true);
   var text=p?.ToString()??"Start Prometheus to inspect the local model inventory.";
   MessageBox.Show(this,"Automatic RAM adaptation is enabled. Prometheus rechecks available memory when a session starts. CPU threads and context are bounded; explicit --model selections are respected.\n\n"+text,"Prometheus hardware settings",MessageBoxButton.OK,MessageBoxImage.Information);
  }catch(Exception ex){Log(ex.Message);}
 }
 void OnClosing(object? sender,System.ComponentModel.CancelEventArgs e){
  if(_operationActive||_ejecting||_repairing){e.Cancel=true;Log("Wait for the current operation to finish before closing.");return;}
  _timer.Stop();_arrivalTimer.Stop();
  if(Environment.GetCommandLineArgs().Contains("--verify-layout"))return;
  try{var path=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Prometheus","controller-intentional-close.flag");Directory.CreateDirectory(Path.GetDirectoryName(path)!);File.WriteAllText(path,DateTime.UtcNow.ToString("o"));}catch(Exception ex){Log(ex.Message);}
 }

}