using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Media;
namespace Prometheus.DriveController;
public partial class MainWindow:Window{
 readonly LegacyControllerBridge _bridge=new(); readonly StartupProbe _probe=new();
 static readonly Brush Green=new SolidColorBrush(Color.FromRgb(25,195,125)), Yellow=new SolidColorBrush(Color.FromRgb(228,183,44)), Red=new SolidColorBrush(Color.FromRgb(239,68,68)), Muted=new SolidColorBrush(Color.FromRgb(129,153,170));
 public MainWindow(){InitializeComponent();ShowPlan(ProgressPlan.Startup,null,true);_=RefreshAsync();}
 void Visual(string phase){var b=phase=="green"?Green:phase=="red"?Red:Yellow;StatusBorder.BorderBrush=b;StateText.Foreground=b;EjectText.Foreground=b;}
 void Log(string s){LogText.AppendText($"[{DateTime.Now:HH:mm:ss}] {s}{Environment.NewLine}");LogText.ScrollToEnd();}
 void ShowPlan(IEnumerable<ProgressStep> steps,ISet<string>? completed=null,bool ready=false){var a=steps.Select(x=>x with{Complete=completed?.Contains(x.Name)==true}).ToArray();StepsList.ItemsSource=a.Select(x=>$"{(x.Complete?"✓":"○")}   {Short(x.Name),-29}  {x.Weight,2}%");var pct=ProgressPlan.Percent(a);OverallProgress.Value=ready?100:pct;PercentText.Text=ready?"Ready":$"{pct}%";}
 static string Short(string s)=>s.Replace("Verify Prometheus SSD identity","SSD identity").Replace("Validate portable runtime","Portable runtime").Replace("Start Ollama service","Ollama service").Replace("Load configured model","Model load").Replace("Verify local memory database","Memory database").Replace("Verify portable model store","Model store").Replace("Verify Prometheus source tree","Source tree").Replace("Open chat runtime","Chat runtime");
 async Task RefreshAsync(){var root=_probe.FindPrometheusDrive();DriveInfoText.Text=root==null?"Not detected":$"2.00 TB • Seagate • NTFS • {root}";DeviceText.Text=$"SSD: {(root??"Not detected")}";DriveStateText.Text=root==null?"Missing":"Detected • Ready";var done=await _probe.MeasureAsync(root);UpdateComponents(done);ApplyStatus(await _bridge.RunAsync("status"));}
 void UpdateComponents(ISet<string> d){Set(SsdComponent,"SSD Detection",d.Contains("Verify Prometheus SSD identity"));Set(RuntimeComponent,"Runtime (Python)",d.Contains("Validate portable runtime"));Set(OllamaComponent,"Ollama Service",d.Contains("Start Ollama service"));Set(ModelComponent,"Model Load",d.Contains("Load configured model"));Set(MemoryComponent,"Memory DB",d.Contains("Verify local memory database"));Set(StoreComponent,"Model Store",d.Contains("Verify portable model store"));Set(SourceComponent,"Source Tree",d.Contains("Verify Prometheus source tree"));Set(ChatComponent,"Chat Runtime",d.Contains("Open chat runtime"));}
 void Set(System.Windows.Controls.TextBlock t,string name,bool ok){t.Text=$"● {name} — {(ok?"Ready":"Stopped / unavailable")}";t.Foreground=ok?Green:Muted;}
 void ApplyStatus(BridgeResult r){var s=r.Status;if(s==null){Visual("red");StateText.Text="STATUS: BLOCKED";ActivityText.Text="Controller unavailable. Check details in the log.";OperationText.Text="Error";EjectText.Text="No";Log(r.StdErr.Length>0?r.StdErr:"Unable to parse controller response.");return;}Visual(s.Phase??"yellow");StateText.Text=$"STATUS: {(s.Phase=="green"?"READY":s.Phase?.ToUpperInvariant())}";ActivityText.Text=s.Message??"Prometheus controller";OperationText.Text=s.Activity?.Contains("EJECT",StringComparison.OrdinalIgnoreCase)==true?"Idle":s.Activity??"Checking";EjectText.Text=s.Phase=="green"?"Yes":"No";Log($"Controller: {s.Message} {s.Activity}");StartButton.IsEnabled=s.Phase=="green";StopButton.IsEnabled=s.Phase!="green";}
 async void Start_Click(object sender,RoutedEventArgs e){var sw=Stopwatch.StartNew();StartButton.IsEnabled=false;StopButton.IsEnabled=true;Visual("yellow");StateText.Text="STATUS: STARTING";ActivityText.Text="Measured startup checks are running.";OperationText.Text="Startup";EjectText.Text="No";ShowPlan(ProgressPlan.Startup);Log("Startup requested.");var r=await _bridge.RunAsync("start");ApplyStatus(r);for(int i=0;i<60;i++){var done=await _probe.MeasureAsync();UpdateComponents(done);ShowPlan(ProgressPlan.Startup,done);if(done.Count==ProgressPlan.Startup.Length){sw.Stop();Visual("yellow");StateText.Text="STATUS: RUNNING";ActivityText.Text="All measured startup checks passed.";OperationText.Text="Running";EjectText.Text="No";ElapsedText.Text=$"Startup completed in {sw.Elapsed.TotalSeconds:F1} seconds.";StartupTimeText.Text=$"{sw.Elapsed.TotalSeconds:F1} seconds\n{DateTime.Now:g}";Log("All startup measurements passed.");return;}await Task.Delay(500);}sw.Stop();ElapsedText.Text="Startup measurement timed out; controller status retained.";Log("Startup measurement timed out.");}
 async void Stop_Click(object sender,RoutedEventArgs e){var sw=Stopwatch.StartNew();StartButton.IsEnabled=false;StopButton.IsEnabled=false;Visual("yellow");StateText.Text="STATUS: STOPPING / VERIFYING";ActivityText.Text="Graceful shutdown and eject-readiness checks are running.";OperationText.Text="Shutdown";EjectText.Text="No";var done=new HashSet<string>{"Request graceful chat shutdown"};ShowPlan(ProgressPlan.Shutdown,done);Log("Graceful shutdown requested.");var r=await _bridge.RunAsync("stop");sw.Stop();if(r.Status?.Phase=="green"){foreach(var x in ProgressPlan.Shutdown)done.Add(x.Name);ShowPlan(ProgressPlan.Shutdown,done);Visual("green");StateText.Text="STATUS: READY";ActivityText.Text="Prometheus is stopped and verification passed.";OperationText.Text="Idle";EjectText.Text="Yes";ElapsedText.Text=$"Shutdown and verification completed in {sw.Elapsed.TotalSeconds:F1} seconds.";ShutdownTimeText.Text=$"{sw.Elapsed.TotalSeconds:F1} seconds\n{DateTime.Now:g}";VerifyTimeText.Text=$"Passed\n{DateTime.Now:g}";StartButton.IsEnabled=true;Log("Shutdown verified; ready to try Windows Safely Remove/Eject.");var current=await _probe.MeasureAsync();UpdateComponents(current);}else{ApplyStatus(r);ElapsedText.Text="Shutdown blocked; see controller status and log.";Log("Shutdown verification did not reach green.");}}
}