using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Media;
namespace Prometheus.DriveController;
public partial class MainWindow:Window{
 readonly LegacyControllerBridge _bridge=new(); readonly StartupProbe _probe=new();
 static readonly Brush Green=new SolidColorBrush(Color.FromRgb(25,195,125)), Yellow=new SolidColorBrush(Color.FromRgb(228,183,44)), Red=new SolidColorBrush(Color.FromRgb(239,68,68)), Muted=new SolidColorBrush(Color.FromRgb(129,153,170));
 readonly System.Windows.Threading.DispatcherTimer _timer=new(){Interval=TimeSpan.FromSeconds(5)};
 bool _operationActive,_refreshing,_ejecting;
 public MainWindow(){InitializeComponent();ShowPlan(ProgressPlan.Startup);_=RefreshAsync();_timer.Tick+=async(_,_)=>{if(_operationActive||_refreshing||_ejecting)return;_refreshing=true;try{await RefreshAsync();}catch(Exception ex){Visual("red");EjectText.Text="No";Log(ex.Message);}finally{_refreshing=false;}};_timer.Start();var args=Environment.GetCommandLineArgs();if(args.Length==3&&args[1]=="--verify-layout")Loaded+=async(_,_)=>await VerifyLayoutAsync(args[2]);}
 void Visual(string phase){var b=phase=="green"?Green:phase=="red"?Red:Yellow;StatusBorder.BorderBrush=b;StateText.Foreground=b;EjectText.Foreground=b;}
 void Log(string s){LogText.AppendText($"[{DateTime.Now:HH:mm:ss}] {s}{Environment.NewLine}");LogText.ScrollToEnd();}
 IEnumerable<ProgressStep> _plan=ProgressPlan.Startup;
 ISet<string> _lastCompleted=new HashSet<string>();
 bool _startupFailed;
 public sealed record StepRow(string Label,string WeightText,string State,string Icon,Brush Color,int Value,string Detail);
 void ShowPlan(IEnumerable<ProgressStep> steps,ISet<string>? completed=null,bool ready=false){
 _plan=steps;_lastCompleted=completed??new HashSet<string>();
 var a=steps.Select(x=>x with{Complete=_lastCompleted.Contains(x.Name)}).ToArray();
 StepsList.ItemsSource=a.Select(x=>{
 bool error=!x.Complete&&(_startupFailed||(!_operationActive&&x.Name.StartsWith("Verify"))||(!_operationActive&&x.Name.StartsWith("Validate")));
 var state=x.Complete?"Passed":error?"Issue":_operationActive?"Checking":"Stopped";
 return new StepRow(Short(x.Name),$"{x.Weight}%",state,x.Complete?"●":error?"●":"●",x.Complete?Green:error?Red:Yellow,x.Complete?100:0,x.Complete?"Check passed":error?"Check did not pass. See live log.":_operationActive?"Waiting for measured confirmation":"Service stopped or check pending");
 }).ToArray();
 var pct=ProgressPlan.Percent(a);OverallProgress.Value=ready?100:pct;PercentText.Text=ready?"Ready":$"{pct}%";
 }
 static string DriveSummary(string root){try{var di=new DriveInfo(root);double tb=di.TotalSize/1099511627776d,free=di.AvailableFreeSpace/1099511627776d;return $"{tb:F2} TB total • {free:F2} TB free • Seagate • {di.DriveFormat} • {root}";}catch{return $"Seagate • NTFS • {root}";}}
 static string Short(string s)=>s.Replace("Verify Prometheus SSD identity","SSD identity").Replace("Validate portable runtime","Portable runtime").Replace("Start Ollama service","Ollama service").Replace("Load configured model","Model load").Replace("Verify local memory database","Memory database").Replace("Verify portable model store","Model store").Replace("Verify Prometheus source tree","Source tree").Replace("Open chat runtime","Chat runtime");
 async Task RefreshAsync(){var root=_probe.FindPrometheusDrive();DriveInfoText.Text=root==null?"Not detected":DriveSummary(root);DeviceText.Text=$"SSD: {(root??"Not detected")}";if(root==null){DriveStateText.Text="Missing / unreadable";DriveStateText.Foreground=Red;Visual("red");StateText.Text="STATUS: SSD MISSING";ActivityText.Text="Prometheus SSD is not mounted as a readable volume.";EjectText.Text="No";StartButton.IsEnabled=false;StopButton.IsEnabled=false;return;}var health=_probe.DriveHealth(root);DriveStateText.Text=health.Healthy?"● HEALTHY / READY":"● ERROR";DriveStateText.Foreground=health.Healthy?Green:Red;if(!health.Healthy){Visual("red");StateText.Text="STATUS: SSD ERROR";ActivityText.Text=health.Message+" Windows disk repair may be required; Prometheus will not write to the drive until it is readable.";OperationText.Text="Drive health";EjectText.Text="No";StartButton.IsEnabled=false;StopButton.IsEnabled=false;Log("SSD health: "+health.Message);return;}var done=await _probe.MeasureAsync(root);UpdateComponents(done);ShowPlan(ProgressPlan.Startup,done);ApplyStatus(await _bridge.RunAsync("status",root.TrimEnd('\\')));}
 void UpdateComponents(ISet<string> d){Set(SsdComponent,"SSD Detection",d.Contains("Verify Prometheus SSD identity"));Set(RuntimeComponent,"Runtime (Python)",d.Contains("Validate portable runtime"));Set(OllamaComponent,"Ollama Service",d.Contains("Start Ollama service"));Set(ModelComponent,"Model Load",d.Contains("Load configured model"));Set(MemoryComponent,"Memory DB",d.Contains("Verify local memory database"));Set(StoreComponent,"Model Store",d.Contains("Verify portable model store"));Set(SourceComponent,"Source Tree",d.Contains("Verify Prometheus source tree"));Set(ChatComponent,"Chat Runtime",d.Contains("Open chat runtime"));}
 void Set(System.Windows.Controls.TextBlock t,string name,bool ok){t.Text=$"● {name} — {(ok?"Ready":"Stopped / unavailable")}";t.Foreground=ok?Green:Yellow;}
 void ApplyStatus(BridgeResult r){var s=r.Status;if(s==null){Visual("red");StateText.Text="STATUS: BLOCKED";ActivityText.Text="Controller unavailable. Check details in the log.";OperationText.Text="Error";EjectText.Text="No";Log(r.StdErr.Length>0?r.StdErr:"Unable to parse controller response.");return;}Visual(s.Phase??"yellow");StateText.Text=$"STATUS: {(s.Phase=="green"?"READY":s.Phase?.ToUpperInvariant())}";ActivityText.Text=s.Message??"Prometheus controller";OperationText.Text=s.Phase=="green"?"Stopped":s.Phase=="red"?"Blocked":"Running / checking";EjectText.Text="No";Log($"Controller: {s.Message} {s.Activity}");StartButton.IsEnabled=s.Phase=="green";StopButton.IsEnabled=s.Phase!="green";}
 async void Start_Click(object sender,RoutedEventArgs e){if(_operationActive||_refreshing||_ejecting)return;_startupFailed=false;_timer.Start();_operationActive=true;try{var root=_probe.FindPrometheusDrive();if(root==null){await RefreshAsync();return;}var sw=Stopwatch.StartNew();StartButton.IsEnabled=false;StopButton.IsEnabled=true;Visual("yellow");StateText.Text="STATUS: STARTING";ActivityText.Text="Measured startup checks are running.";OperationText.Text="Startup";EjectText.Text="No";ShowPlan(ProgressPlan.Startup);Log("Startup requested.");var r=await _bridge.RunAsync("start",root.TrimEnd('\\'));ApplyStatus(r);for(int i=0;i<60;i++){var done=await _probe.MeasureAsync();UpdateComponents(done);ShowPlan(ProgressPlan.Startup,done);if(done.Count==ProgressPlan.Startup.Length){sw.Stop();Visual("yellow");StateText.Text="STATUS: RUNNING";ActivityText.Text="All measured startup checks passed.";OperationText.Text="Running";EjectText.Text="No";ElapsedText.Text=$"Startup completed in {sw.Elapsed.TotalSeconds:F1} seconds.";StartupTimeText.Text=$"{sw.Elapsed.TotalSeconds:F1} seconds\n{DateTime.Now:g}";Log("All startup measurements passed.");return;}await Task.Delay(500);}sw.Stop();_startupFailed=true;ShowPlan(ProgressPlan.Startup,_lastCompleted);Visual("red");StateText.Text="STATUS: STARTUP INCOMPLETE";ElapsedText.Text="Startup checks timed out; incomplete rows are red.";Log("Startup measurement timed out.");}catch(Exception ex){Visual("red");EjectText.Text="No";Log(ex.Message);}finally{_operationActive=false;}}
 async void Stop_Click(object sender,RoutedEventArgs e){if(_operationActive||_refreshing||_ejecting)return;_operationActive=true;try{var root=_probe.FindPrometheusDrive();if(root==null){await RefreshAsync();return;}var sw=Stopwatch.StartNew();StartButton.IsEnabled=false;StopButton.IsEnabled=false;Visual("yellow");StateText.Text="STATUS: STOPPING / VERIFYING";ActivityText.Text="Graceful shutdown and eject-readiness checks are running.";OperationText.Text="Shutdown";EjectText.Text="No";var done=new HashSet<string>{"Request graceful chat shutdown"};ShowPlan(ProgressPlan.Shutdown,done);Log("Graceful shutdown requested.");var r=await _bridge.RunAsync("stop",root.TrimEnd('\\'));sw.Stop();if(r.Status?.Phase=="green"){foreach(var x in ProgressPlan.Shutdown)done.Add(x.Name);ShowPlan(ProgressPlan.Shutdown,done);Visual("green");StateText.Text="STATUS: READY";ActivityText.Text="Prometheus is stopped and verification passed.";OperationText.Text="Idle";EjectText.Text="No";ElapsedText.Text=$"Shutdown and verification completed in {sw.Elapsed.TotalSeconds:F1} seconds.";ShutdownTimeText.Text=$"{sw.Elapsed.TotalSeconds:F1} seconds\n{DateTime.Now:g}";VerifyTimeText.Text=$"Passed\n{DateTime.Now:g}";StartButton.IsEnabled=true;_timer.Stop();Log("Prometheus stopped. Use Safely Eject SSD to request Windows removal.");ActivityText.Text="Prometheus stopped; Windows has not released the SSD yet.";OperationText.Text="Stopped";}else{ApplyStatus(r);ElapsedText.Text="Shutdown blocked; see controller status and log.";Log("Shutdown verification did not reach green.");}}catch(Exception ex){Visual("red");EjectText.Text="No";Log(ex.Message);}finally{_operationActive=false;}}

 async void Eject_Click(object sender,RoutedEventArgs e){
 if(_operationActive||_refreshing||_ejecting)return;
 _ejecting=true;_timer.Stop();EjectButton.IsEnabled=false;StartButton.IsEnabled=false;StopButton.IsEnabled=false;
 try{
 var root=_probe.FindPrometheusDrive();if(root==null){Log("No mounted Prometheus SSD to eject.");return;}
 Visual("yellow");StateText.Text="STATUS: PREPARING EJECT";ActivityText.Text="Closing chat and verifying databases before Windows removal.";OperationText.Text="Safe eject";EjectText.Text="No";
 var result=await _bridge.RunAsync("stop",root.TrimEnd('\\'));
 Log(result.Status?.Activity??result.StdErr);
 if(result.ExitCode!=0||result.Status==null){Visual("red");StateText.Text="STATUS: EJECT BLOCKED";ActivityText.Text=result.Status?.Message??"Graceful shutdown failed.";return;}
 var script=Path.Combine(AppContext.BaseDirectory,"Prometheus-Safe-Eject.ps1");
 if(!File.Exists(script))throw new FileNotFoundException("Safe eject helper is missing.",script);
 var psi=new ProcessStartInfo("powershell.exe"){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true,WorkingDirectory=AppContext.BaseDirectory};
 foreach(var arg in new[]{"-NoProfile","-ExecutionPolicy","Bypass","-File",script,"-Drive",root.TrimEnd('\\')})psi.ArgumentList.Add(arg);
 using var process=Process.Start(psi)??throw new InvalidOperationException("Could not request Windows removal.");
 var output=process.StandardOutput.ReadToEndAsync();var error=process.StandardError.ReadToEndAsync();await process.WaitForExitAsync();var details=await output;var errors=await error;Log(details+errors);
 if(process.ExitCode==0&&_probe.FindPrometheusDrive()==null){Visual("green");StateText.Text="STATUS: SSD RELEASED";ActivityText.Text="Windows removed the SSD. You can unplug it and connect PRK.";EjectText.Text="Yes";DriveStateText.Text="Released";OperationText.Text="Ejected";ShowPlan(ProgressPlan.Shutdown,new HashSet<string>(ProgressPlan.Shutdown.Select(x=>x.Name)));}
 else{Visual("red");StateText.Text="STATUS: EJECT BLOCKED";ActivityText.Text="Windows still holds the SSD. Keep it connected; see the veto details in the live log.";OperationText.Text="Windows veto";EjectText.Text="No";}
 }catch(Exception ex){Visual("red");StateText.Text="STATUS: EJECT ERROR";EjectText.Text="No";Log(ex.Message);}
 finally{_ejecting=false;EjectButton.IsEnabled=true;StartButton.IsEnabled=_probe.FindPrometheusDrive()!=null;}
 }
}