using System; using System.Diagnostics; using System.IO; using System.Text.Json; using System.Windows; using System.Windows.Controls; using System.Windows.Media;
namespace Prometheus.PRK.Controller;
public partial class MainWindow:Window {
 string Root=>Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..")); string Tool=>Path.Combine(Root,"tools","Prometheus-PRK-SelfRepair.ps1"); string Drive=>Path.GetPathRoot(Root)??"";
 public MainWindow(){InitializeComponent();Loaded+=(_,__)=>RefreshHealth();}
 string Run(string action){var a=$"-NoProfile -ExecutionPolicy Bypass -File \"{Tool}\" -Action {action} -Drive \"{Drive.TrimEnd('\\')}\"";var p=new ProcessStartInfo("powershell.exe",a){UseShellExecute=false,RedirectStandardOutput=true,CreateNoWindow=true};using var x=Process.Start(p)!;var s=x.StandardOutput.ReadToEnd();x.WaitForExit();if(x.ExitCode!=0)throw new Exception("Recovery engine failed.");return s;}
 Brush B(string state)=>new SolidColorBrush((Color)ColorConverter.ConvertFromString(state is "ready" or "armed"?"#35D07F":state is "repairable"?"#E4B72C":"#E34D59"));
 void RefreshHealth(){try{using var j=JsonDocument.Parse(Run("health"));var r=j.RootElement;HealthPanel.Children.Clear();var bad=false;foreach(var c in r.GetProperty("channels").EnumerateArray()){var name=c.GetProperty("name").GetString()??"";var state=c.GetProperty("state").GetString()??"";var pct=c.GetProperty("percent").GetInt32();var detail=c.GetProperty("detail").GetString()??"";if(state is "error" or "blocked")bad=true;var g=new Grid{Margin=new Thickness(0,3,0,5)};g.RowDefinitions.Add(new RowDefinition());g.RowDefinitions.Add(new RowDefinition());g.RowDefinitions.Add(new RowDefinition());g.ColumnDefinitions.Add(new ColumnDefinition());g.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(150)});var n=new TextBlock{Text=name.Replace("_"," ").ToUpperInvariant(),FontWeight=FontWeights.Bold};var s=new TextBlock{Text=$"{pct}% - {state.ToUpperInvariant()}",Foreground=B(state),FontWeight=FontWeights.Bold,HorizontalAlignment=HorizontalAlignment.Right};Grid.SetColumn(s,1);var bar=new ProgressBar{Minimum=0,Maximum=100,Value=pct,Height=10,Margin=new Thickness(0,3,0,2),Foreground=B(state)};Grid.SetRow(bar,1);Grid.SetColumnSpan(bar,2);var dt=new TextBlock{Text=detail,Foreground=new SolidColorBrush((Color)ColorConverter.ConvertFromString("#AFC2D0")),FontSize=11};Grid.SetRow(dt,2);Grid.SetColumnSpan(dt,2);g.Children.Add(n);g.Children.Add(s);g.Children.Add(bar);g.Children.Add(dt);HealthPanel.Children.Add(g);}StatusText.Text=bad?"STATUS: ATTENTION REQUIRED":"STATUS: RECOVERY KEY READY";StatusBorder.BorderBrush=B(bad?"error":"ready");StatusText.Foreground=StatusBorder.BorderBrush;FileText.Text=$"{r.GetProperty("protected_files").GetInt32()} protected files";DetailText.Text=bad?"Self-repair is blocked or a channel failed. Review health details.":"Live health verified. Self-repair is armed.";}catch(Exception ex){StatusText.Text="STATUS: CONTROLLER ERROR";StatusText.Foreground=B("error");StatusBorder.BorderBrush=B("error");DetailText.Text=ex.Message;}}
 void Refresh_Click(object s,RoutedEventArgs e)=>RefreshHealth(); void Repair_Click(object s,RoutedEventArgs e){try{Run("repair");RefreshHealth();}catch(Exception ex){MessageBox.Show(ex.Message,"Prometheus PRK");}} void Verify_Click(object s,RoutedEventArgs e)=>RefreshHealth();
 void Eject_Click(object s,RoutedEventArgs e){try{var answer=MessageBox.Show("This will verify and stage recovery, then close PRK-backed processes and remote management last. Continue?","Prepare Recovery Key for Eject",MessageBoxButton.YesNo,MessageBoxImage.Warning);if(answer!=MessageBoxResult.Yes)return;StatusText.Text="STATUS: PREPARING FOR EJECT";StatusText.Foreground=B("repairable");StatusBorder.BorderBrush=B("repairable");DetailText.Text="Verifying and staging recovery before handoff...";var verify=Run("health");using(var j=JsonDocument.Parse(verify)){if(!j.RootElement.GetProperty("source_verified").GetBoolean())throw new Exception("Eject blocked: Recovery Key integrity verification failed.");}var prk=Path.Combine(Root,"tools","Prometheus-Recovery-Key.ps1");var local=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Prometheus");Directory.CreateDirectory(local);var eject=Path.Combine(local,"Prometheus-Removable-Eject.ps1");var sourceEject=Path.Combine(Root,"tools","Prometheus-Removable-Eject.ps1");File.Copy(sourceEject,eject,true);var handoff=Path.Combine(local,"PRK-Eject-Handoff.ps1");File.WriteAllText(handoff,"param([string]$Drive)\r\n$ErrorActionPreference='Stop'\r\n& powershell.exe -NoProfile -ExecutionPolicy Bypass -File '"+prk.Replace("'","''")+"' -Action stage -Drive $Drive | Out-Null\r\n& powershell.exe -NoProfile -ExecutionPolicy Bypass -File '"+eject.Replace("'","''")+"' -Drive $Drive\r\nexit $LASTEXITCODE\r\n");Process.Start(new ProcessStartInfo("powershell.exe",$"-NoProfile -ExecutionPolicy Bypass -File \"{handoff}\" -Drive \"{Drive.TrimEnd('\\')}\""){UseShellExecute=true,WorkingDirectory=local});StatusText.Text="STATUS: EJECT HANDOFF STARTED";DetailText.Text="Windows-side handoff is staging recovery and closing PRK-backed processes. Wait for the safe-remove indication.";Close();}catch(Exception ex){StatusText.Text="STATUS: EJECT BLOCKED";StatusText.Foreground=B("error");StatusBorder.BorderBrush=B("error");DetailText.Text=ex.Message;}}

}