param([ValidateSet('ui','status','start','stop','eject')][string]$Action='ui',[string]$Drive)
$ErrorActionPreference='Stop'
function Find-Drive { if($Drive){return $Drive.TrimEnd('\')} ; foreach($d in Get-CimInstance Win32_LogicalDisk|Where-Object {$_.DeviceID -ne $env:SystemDrive}){if(Test-Path ($d.DeviceID+'\Prometheus-Flash-Kit')){return $d.DeviceID};if($d.VolumeName -eq 'Prometheus-2TB'){return $d.DeviceID}};throw 'Prometheus removable drive not found.' }
function State { $d=Find-Drive;$ld=Get-CimInstance Win32_LogicalDisk -Filter ("DeviceID='"+$d+"'");$mode=if($ld.VolumeName -eq 'Prometheus-2TB'){'FULL SYSTEM'}else{'PORTABLE SYSTEM'};$kit=if($mode -eq 'FULL SYSTEM'){$d+'\'}else{$d+'\Prometheus-Flash-Kit'};$healthy=(Test-Path $kit);$dc=@(Get-CimInstance Win32_Process|Where-Object {$_.CommandLine -match 'DesktopCommanderStartup|desktop-commander'}).Count -gt 0;$sup=@(Get-CimInstance Win32_Process|Where-Object {$_.CommandLine -match 'Prometheus-USB-Supervisor\.ps1'}).Count -gt 0;[pscustomobject]@{Drive=$d;Mode=$mode;Healthy=$healthy;FileSystem=$ld.FileSystem;SizeGB=[math]::Round($ld.Size/1GB,1);Commander=$dc;Supervisor=$sup;Kit=$kit} }
function Start-Prometheus($s){$runner=Join-Path $env:LOCALAPPDATA 'DesktopCommanderStartup\Run-DesktopCommander.ps1';if(!$s.Commander -and (Test-Path $runner)){Start-Process powershell.exe -ArgumentList '-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',$runner -WindowStyle Hidden};if($s.Mode -eq 'FULL SYSTEM'){$launch=$s.Drive+'\START-PROMETHEUS-SSD.cmd'}else{$launch=Join-Path $s.Kit 'START_PROMETHEUS.cmd'};if(Test-Path $launch){Start-Process $launch}else{throw 'Prometheus launcher is missing.'}}
function Stop-Prometheus($s){if($s.Mode -eq 'FULL SYSTEM'){$engine=$s.Drive+'\Prometheus-Controller-v0.5.2\Prometheus-Drive-Engine.ps1';if(Test-Path $engine){& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $engine stop -Drive $s.Drive}}else{Get-CimInstance Win32_Process|Where-Object {$_.ProcessId -ne $PID -and (($_.ExecutablePath -and $_.ExecutablePath.StartsWith($s.Drive+'\',[StringComparison]::OrdinalIgnoreCase)) -or ($_.CommandLine -and $_.CommandLine.Contains($s.Drive+'\')))}|ForEach-Object {Stop-Process -Id $_.ProcessId -Force}}}
$s=State
if($Action -eq 'status'){$s|ConvertTo-Json;exit}
if($Action -eq 'start'){Start-Prometheus $s;exit}
if($Action -eq 'stop'){Stop-Prometheus $s;exit}
if($Action -eq 'eject'){$handoff=if($s.Mode -eq 'FULL SYSTEM'){Join-Path $env:LOCALAPPDATA 'Prometheus\Controllers\Prometheus-Controller-v0.5.2\Prometheus-Eject-Handoff.ps1'}else{Join-Path $env:LOCALAPPDATA 'Prometheus\Prometheus-Removable-Eject.ps1'};if(!(Test-Path $handoff)){throw 'Safe-eject handoff is unavailable on Windows.'};Start-Process powershell.exe -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File',$handoff,'-Drive',$s.Drive -WindowStyle Hidden;exit}
Add-Type -AssemblyName PresentationFramework
$w=New-Object Windows.Window;$w.Title='Prometheus Portable Control Center';$w.Width=590;$w.Height=590;$w.WindowStartupLocation='CenterScreen'
$g=New-Object Windows.Controls.StackPanel;$g.Margin='28';$w.Content=$g
function T($text,$size=16,$weight='Normal'){$x=New-Object Windows.Controls.TextBlock;$x.Text=$text;$x.FontSize=$size;$x.FontWeight=$weight;$x.Margin='0,5,0,5';$g.Children.Add($x)|Out-Null}
T 'PROMETHEUS' 30 'Bold';T ('PORTABLE CONTROL CENTER  •  '+$s.Mode) 15 'Bold';T '';T ('DRIVE   '+$(if($s.Healthy){'● HEALTHY / READY'}else{'● ERROR'})) 19 'Bold';T ($s.FileSystem+' • '+$s.SizeGB+' GB • '+$s.Drive);T ('Desktop Commander   '+$(if($s.Commander){'● Connected'}else{'○ Not connected'}));T ('USB Supervisor      '+$(if($s.Supervisor){'● Running'}else{'○ Not running'}));T '';T ($(if($s.Mode -eq 'PORTABLE SYSTEM'){'Portable core available. SSD-only Ollama/Kiwix resources are not present.'}else{'Full SSD capabilities available.'})) 14
foreach($spec in @(@('▶  START PROMETHEUS','start'),@('■  STOP PROMETHEUS','stop'),@('⏏  PREPARE FOR EJECT','eject'))){$b=New-Object Windows.Controls.Button;$b.Content=$spec[0];$b.Height=55;$b.Margin='0,8,0,0';$a=$spec[1];$b.Add_Click({param($sender,$e)& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $PSCommandPath -Action $sender.Tag -Drive $s.Drive}.GetNewClosure());$b.Tag=$a;$g.Children.Add($b)|Out-Null}
T '';T 'Eject will refuse to disconnect remote management if a drive-backed process remains.' 12
$w.ShowDialog()|Out-Null
